services:
  sqlDb:
    image: mysql:latest
    ports:
      - 3306
    volumes:
      - database-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: mediscreenDB


  mongoDb:
    image: mongo:latest
    ports:
      - 27017
    volumes:
      - database-volume:/var/lib/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mediscreen-eureka:
    image: mediscreen-eureka:1.0.0
    ports:
      - "8761:8761"

  mediscreen-central:
    image: mediscreen-central:1.0.0
    ports:
      - "8090:8090"
    depends_on:
      - mediscreen-patient
      - mediscreen-notes
      - mediscreen-risk
      - mediscreen-eureka

  mediscreen-patient:
    image: mediscreen-patient:1.0.0
    ports:
      - "8081:8081"
    depends_on:
      - sqlDb
      - mediscreen-eureka


  mediscreen-notes:
    image: mediscreen-notes:1.0.0
    ports:
      - "8082:8082"
    depends_on:
      - mongoDb
      - mediscreen-patient
      - mediscreen-eureka

  mediscreen-risk:
    image: mediscreen-risk:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - mediscreen-patient
      - mediscreen-notes
      - mediscreen-eureka

volumes:
  database-volume: