services:
  database:
    image: mysql:latest
    ports:
        - 127.0.0.1:3306/3306
    volumes:
      - database-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: mediscreenDB

  mediscreen-central:
    image: mediscreen-central:1.0.0
    ports:
      - "8090:8090"
    depends_on:
      - mediscreen-patient
      - mediscreen-notes
      - mediscreen-risk
      - mediscreen-eureka

  mediscreen-patient:
    image: mediscreen-patient:1.0.0
    ports:
      - "8081:8081"
    depends-on:
      - database
      - mediscreen-eureka

  mediscreen-notes:
    image: mediscreen-notes:1.0.0
    ports:
      - "8082:8082"
    depends_on:
      - mediscreen-patient
      - mediscreen-eureka

  mediscreen-risk:
    image: mediscreen-risk:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - mediscreen-patient
      - mediscreen-notes
      - mediscreen-eureka

  mediscreen-eureka:
    image: mediscreen-eureka:1.0.0
    ports:
      - "8761:8761"
