
logging:
  level:
    com.mediscreen.central: DEBUG
server:
  port: 8090
spring:
  application:
    name: mediscreen-client
  cloud:
    gateway:
      routes:
        - id: mediscreen-patient
          uri: lb://mediscreen-patient
          predicates:
            - Path=/patient/**


        - id: mediscreen_notes
          uri: lb://mediscreen-notes
          predicates:
            - Path=/pat-notes/**

        - id: mediscreen-diabetesRiskService
          uri: lb://mediscreen-assess
          predicates:
              - Path=/assess/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true





eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}-${random.uuid}




